apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

bases:
- github.com/Innervate/secret-sync-operator//deploy

resources:
- remote_cluster_creds.yaml
- synced_secret.yaml
