apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secret-sync-operator

bases:
- github.com/Innervate/secret-sync-operator//deploy

resources:
- namespace.yaml
- remote_cluster_creds.yaml
- synced_secret.yaml
