apiVersion: v1
kind: Secret
metadata:
  name: secret-sync-remote-cluster-creds
type: Opaque
data:
  # Host for accessing the remote cluster's API
  #   echo -n "https://some.cluster.example.com:443" | base64
  host: REPLACE_WITH_HOST

  # Base64 encoded CA for your remote cluster, you should be able to copy this
  # directly from your ~/.kube/config file
  ca: REPLACE_WITH_CA

  # Access token for the service account that you want to use when syncing secrets.
  # This should be a read-only user that can only access the specific secret(s) you
  # want to sync (eg SSL keys).
  token: REPLACE_WITH_TOKEN
