---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sync-operator-agent
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-sync-operator-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["my-secret-to-distribute", "my-secret-to-distribute2"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-sync-operator-agent
subjects:
- kind: ServiceAccount
  name: secret-sync-operator-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-sync-operator-role
