// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteSecretSpec) DeepCopyInto(out *RemoteSecretSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteSecretSpec.
func (in *RemoteSecretSpec) DeepCopy() *RemoteSecretSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynchronizedSecret) DeepCopyInto(out *SynchronizedSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynchronizedSecret.
func (in *SynchronizedSecret) DeepCopy() *SynchronizedSecret {
	if in == nil {
		return nil
	}
	out := new(SynchronizedSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SynchronizedSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynchronizedSecretList) DeepCopyInto(out *SynchronizedSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SynchronizedSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynchronizedSecretList.
func (in *SynchronizedSecretList) DeepCopy() *SynchronizedSecretList {
	if in == nil {
		return nil
	}
	out := new(SynchronizedSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SynchronizedSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynchronizedSecretSpec) DeepCopyInto(out *SynchronizedSecretSpec) {
	*out = *in
	out.RemoteSecret = in.RemoteSecret
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynchronizedSecretSpec.
func (in *SynchronizedSecretSpec) DeepCopy() *SynchronizedSecretSpec {
	if in == nil {
		return nil
	}
	out := new(SynchronizedSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynchronizedSecretStatus) DeepCopyInto(out *SynchronizedSecretStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynchronizedSecretStatus.
func (in *SynchronizedSecretStatus) DeepCopy() *SynchronizedSecretStatus {
	if in == nil {
		return nil
	}
	out := new(SynchronizedSecretStatus)
	in.DeepCopyInto(out)
	return out
}
